language: generic
sudo: false
deploy:
    -   provider: releases
        api_key:
            secure: "sSItwiT7w7q4zH5oOPxb5sJbdYgZ3tl7yppeKymEOwtDJI8jcoQRcb5YFOJuKkITleoABASIaR9RX08H4msks3o+9tpvLr+DMnuxGYd06XM0NQSbMxzYKgNcOTOBAJq4Rz0+g/9HGUh/cIk11wN6uV1uyJalz4+eIfBVJOHD/ZkWIJOCB8MED+NotaD4hZ26AQXwtCTbyTWgSx/0nlN2/cgezg9Ek6YwtWHr7FKQmKbxXGefDGuii7qKv9brJSHzs/Ju1dMXMggnCbi1w91leNX4OcSL31lKP2fV627YOAmaFxgVhC4650sa/FjWuLUt1WZf/3x89GLkwyATy6wXBBU/nqOgEtyvjO2648pBn2uQkfORZBzgmS1QXd1oNl+7iMY9FRFPXUCWDrxyJH2eju2ZQamClnHeSufgyM5riQrfTVNw9NIDJmPYRKxKf5Qln0uZikZlAgoC5sw/6tjbgj6AU2FLQg2Em7NqHiCkP5Tgzrn9xeDw310T/t0zSimrOD4RtxgOE4SKey0/76oup1wcSFcgX2FizvAmhphlwoV9BxR2Lm021V7CHOgezXbKI+hqqHoN/sAFgp0C5J1fEDFSIkWAZi7lGoVVpdPFoBPgbeuyK7LzDPCCp5zgI+utgFfbJmszkvatRzCvfLd18pzs2eL19UtBYS7dwUr6WIg="
        file_glob: true
        file: /tmp/packages/*
        skip_cleanup: true
        on:
            tags: true

before_install:
    - ./ci/before-install.sh
script:
    - ./ci/script.sh
